CREATE TABLE "attachments" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "body" bytea NOT NULL,
  "post_id" int NOT NULL,
  "status" varchar(20) NOT NULL DEFAULT 'Active'
);

CREATE TABLE "posts" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "body" varchar(500) NOT NULL,
  "position" int NOT NULL,
  "timestamp" timestamp NOT NULL,
  "subject_id" int NOT NULL,
  "owner_id" int NOT NULL,
  "status" varchar(20) NOT null default 'Active',
  "folder_id" int NOT NULL
);

CREATE TABLE "subject" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "name" varchar(500) NOT NULL,
  "theme_id" int NOT NULL,
  "status" varchar(20) NOT NULL DEFAULT 'Active'
);

CREATE TABLE "themes" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "name" varchar(200) NOT NULL DEFAULT 'Default Theme',
  "first_color" varchar(50),
  "secondary_color" varchar(50),
  "buttons_color" varchar(50),
  "status" varchar(20) NOT NULL DEFAULT 'Active'
);

CREATE TABLE "folders" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "foldername" varchar(200) NOT NULL DEFAULT 'New Folder',
  "position" int NOT NULL,
  "status" varchar(20) NOT NULL DEFAULT 'Active',
  "user_id" int NOT NULL
);

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "firstname" varchar(200) NOT NULL,
  "lastname" varchar(200) NOT NULL,
  "pw" varchar(200) NOT NULL,
  "email" varchar(200) NOT NULL,
  "role" varchar(20) NOT NULL,
  "status" varchar(50) NOT NULL DEFAULT 'Active'
);

CREATE TABLE "session" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "hash" varchar(700) NOT NULL,
  "user_id" int NOT NULL,
  "status" varchar(20) NOT null DEDFAULT 'Active',
  "datetime_created" timestamp NOT NULL
);

ALTER TABLE "attachments" ADD CONSTRAINT "attachments_to_post_posts" FOREIGN KEY ("post_id") REFERENCES "posts" ("id");

ALTER TABLE "posts" ADD CONSTRAINT "posts_subject" FOREIGN KEY ("subject_id") REFERENCES "subject" ("id");

ALTER TABLE "folders" ADD CONSTRAINT "folders_users" FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "posts" ADD CONSTRAINT "folder_posts" FOREIGN KEY ("folder_id") REFERENCES "folders" ("id");

ALTER TABLE "subject" ADD CONSTRAINT "theme_to_subject" FOREIGN KEY ("theme_id") REFERENCES "themes" ("id");

ALTER TABLE "session" ADD CONSTRAINT "user_to_session" FOREIGN KEY ("user_id") REFERENCES "users" ("id");
