CREATE TABLE "attachments" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "body" bytea NOT NULL,
  "post_id" int NOT NULL,
  "status" varchar(20) NOT NULL DEFAULT 'Active'
);

CREATE TABLE "posts" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "subject" varchar(200) NOT NULL,
  "body" text NOT NULL,
  "position" int NOT NULL DEFAULT 1,
  "timestamp" timestamp NOT NULL,
  "chapter_id" int NOT NULL,
  "status" varchar(20) NOT NULL
);

CREATE TABLE "chapters" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "name" varchar(500) NOT NULL,
  "theme_id" int NOT NULL,
  "position" int NOT NULL DEFAULT 1,
  "status" varchar(20) NOT NULL DEFAULT 'Active',
  "folder_id" int NOT NULL
);

CREATE TABLE "themes" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "name" varchar(200) NOT NULL DEFAULT 'Default Theme',
  "first_color" varchar(50),
  "secondary_color" varchar(50),
  "buttons_color" varchar(50),
  "status" varchar(20) NOT NULL DEFAULT 'Active'
);

CREATE TABLE "folders" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "foldername" varchar(200) NOT NULL DEFAULT 'New Folder',
  "position" int NOT NULL DEEFAULT 1,
  "status" varchar(20) NOT NULL DEFAULT 'Active',
  "user_id" int NOT NULL
);

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "firstname" varchar(200) NOT NULL,
  "lastname" varchar(200) NOT NULL,
  "pw" varchar(200) NOT NULL,
  "email" varchar(200) NOT NULL,
  "role_id" int NOT NULL,
  "status" varchar(50) NOT NULL DEFAULT 'Active'
);

CREATE TABLE "roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "name" varchar(50) NOT NULL,
  "permissions" varchar(500)
);

CREATE TABLE "session" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "hash" varchar(700) NOT NULL,
  "user_id" int NOT NULL,
  "status" varchar(20) NOT NULL,
  "datetime_created" timestamp NOT NULL
);

ALTER TABLE "attachments" ADD CONSTRAINT "attachments_to_post_posts" FOREIGN KEY ("post_id") REFERENCES "posts" ("id");

ALTER TABLE "folders" ADD CONSTRAINT "folders_to_users" FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "session" ADD CONSTRAINT "user_to_session" FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "posts" ADD CONSTRAINT "chapter_to_post" FOREIGN KEY ("chapter_id") REFERENCES "chapters" ("id");

ALTER TABLE "chapters" ADD CONSTRAINT "folder_to_chapter" FOREIGN KEY ("folder_id") REFERENCES "folders" ("id");

ALTER TABLE "chapters" ADD CONSTRAINT "theme_to_chapter" FOREIGN KEY ("theme_id") REFERENCES "themes" ("id");

ALTER TABLE "users" ADD CONSTRAINT "role_to_user" FOREIGN KEY ("role_id") REFERENCES "roles" ("id");
